CREATE TABLE IF NOT EXISTS appearance_config (
  config_key VARCHAR(120) NOT NULL PRIMARY KEY,
  config_json LONGTEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
